version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mrivals-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mrivals_builder_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mrivals_network

  mrivals-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrivals-api
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}

      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      AI_BASE_URL: ${AI_BASE_URL}
      AI_PRIVATE_KEY: ${AI_PRIVATE_KEY}
    ports:
      - "9092:8080"
    networks:
      - mrivals_network

volumes:
  mysql_data:

networks:
  mrivals_network:
    external: true
