version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mrivals-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mrivals_builder_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - traefik-network

  mrivals-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrivals-api
    expose:
      - "8080"   # 🔥 obligatoire pour Traefik
    restart: always
    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      API_KEY: ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}

      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      AI_BASE_URL: ${AI_BASE_URL}
      AI_PRIVATE_KEY: ${AI_PRIVATE_KEY}

    labels:
      - "traefik.enable=true"

      # ROUTEUR API : https://mrivals-builder.com/api/...
      - "traefik.http.routers.mrivals-api.rule=Host(`mrivals-builder.com`, `www.mrivals-builder.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.mrivals-api.entrypoints=websecure"
      - "traefik.http.routers.mrivals-api.tls.certresolver=le"
      - "traefik.http.routers.mrivals-api.tls=true"


      # Enlever /api pour Spring Boot
      - "traefik.http.middlewares.mrivals-strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.mrivals-api.middlewares=mrivals-strip-api@docker"

      # Service (port interne Spring)
      - "traefik.http.services.mrivals-api.loadbalancer.server.port=8080"

    networks:
      - traefik-network

volumes:
  mysql_data:

networks:
  traefik-network:
    external: true
    name: traefik_traefik-network
