spring.application.name=Mrivals-Builder

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

cors.allowed-origins=${ALLOWED_ORIGINS}

api.base.url=https://marvelrivalsapi.com/api/v1
api.key=${API_KEY}

app.jwt.expiration=1d
app.jwt.secret=${JWT_SECRET}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop